-- Kayseri Ticaret MTAL Kariyer Portalı
-- SIFIRDAN BOŞ SUPABASE PROJESİ için temel şema.
-- Sıra: 00_BASE_SCHEMA.sql -> migration_v3.sql -> migration_v4.sql

create extension if not exists pgcrypto;

create table if not exists teachers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  password text not null,
  role text not null default 'teacher' check (role in ('teacher','admin')),
  created_at timestamptz not null default now()
);

create table if not exists students (
  id text primary key,
  student_no text unique,
  student_key text,
  pin_hash text,
  name text not null,
  class_name text,
  phone text,
  address text,
  candidate_kind text default 'Öğrenci',
  target_area text default 'Muhasebe',
  features text[] default '{}'::text[],
  scales_json jsonb default '{}'::jsonb,
  note text,
  status text default 'Aktif aday',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists workplace_requests (
  id text primary key,
  title text not null,
  person text,
  phone text,
  email text,
  address text,
  sector text default 'Stajyer Öğrenci',
  quota integer not null default 1 check (quota between 1 and 99),
  days text[] default '{}'::text[],
  features text[] default '{}'::text[],
  skill_levels jsonb default '{}'::jsonb,
  note text,
  status text default 'Aktif',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists student_applications (
  id text primary key,
  request_id text not null,
  student_id text,
  student_name text,
  student_class text,
  phone text,
  type text default 'Başvuru',
  source text default 'Aday',
  teacher text,
  status text default 'Yeni',
  note text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists student_placements (
  id text primary key,
  request_id text not null,
  student_id text,
  status text default 'Yerleştirildi',
  note text default '',
  teacher text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists external_jobs (
  id text primary key,
  title text not null,
  company text,
  district text default 'Kayseri',
  source text,
  url text not null,
  kind text default 'muhasebe',
  description text,
  published_at timestamptz default now(),
  is_active boolean default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Foreign key'ler mevcut v3 verileriyle uyumlu olacak şekilde yumuşak bırakılmıştır.
-- API tarafı ilişkileri request_id/student_id üzerinden doğrular.

create unique index if not exists students_student_no_unique
  on students(student_no)
  where student_no is not null and student_no <> '';
create index if not exists students_name_idx on students(name);
create index if not exists students_status_idx on students(status);
create index if not exists workplace_requests_status_created_idx on workplace_requests(status, created_at desc);
create index if not exists student_applications_request_idx on student_applications(request_id, created_at desc);
create index if not exists student_applications_student_idx on student_applications(student_id, created_at desc);
create index if not exists student_placements_request_idx on student_placements(request_id, created_at desc);
create index if not exists student_placements_student_idx on student_placements(student_id, created_at desc);
create index if not exists external_jobs_active_date_idx on external_jobs(is_active, published_at desc);

alter table teachers enable row level security;
alter table students enable row level security;
alter table workplace_requests enable row level security;
alter table student_applications enable row level security;
alter table student_placements enable row level security;
alter table external_jobs enable row level security;

drop policy if exists "public external jobs read" on external_jobs;
create policy "public external jobs read" on external_jobs
  for select using (is_active = true);

-- İlk giriş için geçici hesaplar.
-- ŞİFRE: 123456
-- İlk başarılı girişten sonra bu şifreleri değiştirmeniz önerilir.
insert into teachers(name,password,role)
select 'Koordinatör', 'sha256:' || encode(digest('123456','sha256'),'hex'), 'teacher'
where not exists (select 1 from teachers);

insert into teachers(name,password,role)
select 'Yönetici', 'sha256:' || encode(digest('123456','sha256'),'hex'), 'admin'
where not exists (select 1 from teachers where role='admin');
